services:
  jupyter:
    build:
      context: .
      dockerfile: jupyter/Dockerfiles
      args:
        - APPUSER_UID=${APPUSER_UID}
        - APPUSER_GID=${APPUSER_GID}
        - APPUSER_NAME=${APPUSER_NAME}
        - PYTHON_VERSION=${PYTHON_VERSION}
        - PIP_VERSION=${PIP_VERSION}
    image: llm-rag-examples-jupyter:0.0.1
    container_name: llm-rag-examples-jupyter
    hostname: llm-rag-examples-jupyter
    tty: true
    stdin_open: true
    ports:
      - 8888:8888
    volumes:
      - ./.aws:/home/${APPUSER_NAME}/.aws
      - ./jupyter/requirements.txt:/home/${APPUSER_NAME}/requirements.txt
      - ./jupyter/notebooks:/home/${APPUSER_NAME}/notebooks
    user: ${APPUSER_NAME}
    environment:
      - APPUSER_NAME=${APPUSER_NAME}
      - AWS_PROFILE=${AWS_PROFILE}
    command:
      - /home/${APPUSER_NAME}/jupyter.sh
    
