services:
  ollama:
    image: ollama/ollama:0.5.7
    container_name: llm-rag-examples-ollama
    hostname: llm-rag-examples-ollama
    ports:
      - 11434:11434
    volumes:
      - ./ollama/data:/root/.ollama
      - ./ollama/work:/root/work
  jupyter:
    build:
      context: .
      dockerfile: jupyter/Dockerfiles
      args:
        - APPUSER_UID=${APPUSER_UID}
        - APPUSER_GID=${APPUSER_GID}
        - APPUSER_NAME=${APPUSER_NAME}
        - PYTHON_VERSION=${PYTHON_VERSION}
    image: llm-rag-examples-jupyter:0.0.1
    container_name: llm-rag-examples-jupyter
    hostname: llm-rag-examples-jupyter
    tty: true
    stdin_open: true
    ports:
      - 8888:8888
    volumes:
      - ./.aws:/home/${APPUSER_NAME}/.aws
      - ./jupyter/requirements.txt:/home/${APPUSER_NAME}/requirements.txt
      - ./jupyter/notebooks:/home/${APPUSER_NAME}/notebooks
      - ./jupyter/.venv:/home/${APPUSER_NAME}/.venv
    user: ${APPUSER_NAME}
    environment:
      - APPUSER_NAME=${APPUSER_NAME}
      - AWS_PROFILE=${AWS_PROFILE}
      - PIP_VERSION=${PIP_VERSION}
      - BACKLOG_API_KEY=${BACKLOG_API_KEY}
    command:
      - /home/${APPUSER_NAME}/startup.sh
