CREATE TABLE IF NOT EXISTS text_embeddings (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    text VARCHAR(255) NOT NULL,
    embedding VECTOR(4096) NOT NULL,
    metadata JSON,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
